try {
    hello();
} catch (error) {
    console.log(error)
}


try {
    anotherFunction();
} catch {
    console.log('Ha ocurrido un error')
}